config/routes.rb
Portfolio::Application.routes.draw do
  devise_for :users, controllers: {registrations: "devise/registrations",
                           passwords: "users/passwords",
                           omniauth_callbacks: "omniauth_callbacks"}

  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'

  resources :posts do
    resources :comments
  end

  resources :projects do
    resources :comments
  end

  root 'home#index'

  resources :comments

  resources :messages

  namespace :api do
    namespace :v1 do
      resources :posts, :only => [ :create ]
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "My Portfolio" %></title>
    <title>Portfolio</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <% flash.each do |key, value| %>
    <div class="alert-box round <%= flash_class(key) %>">
      <%= value %>
    </div>
  <% end %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <body>

    <nav class="top-bar">
      <ul class="title-area">
        <li class="name">
          <h1><%= link_to "Postings", posts_path %></a></h1>
          <li class="divider"></li>

        </li>
      </ul>
      <section class="top-bar-section">
        <ul class="right">
          <li class="divider"></li>
          <li><%= link_to "Projects", projects_path %></li>
          <li class="divider"></li>
          <li><%= link_to "Contact Us", new_message_path %></li>
          <li class="divider"></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li class="divider"></li>
          <li><% if current_user.present? %></li>
  <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
              <% else %>
              <li><%= link_to "Sign In", new_user_session_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter) %></li>
              <% end %>
        </ul>
      </section>
  </nav>

  <div class="row">
    <div class="small-8 columns"><%= yield %></div>
    <div class="small-4 columns">
      <h3 class="subheader">Site Purpose</h3>
    <I>This is a work in progress for a Rails programming class, and all content is subject to change. All projects shown in this site are purely fictitious.</I>
    </div>
  </div>

  <script src="/assets/jquery.js"></script>
  <script src="/assets/foundation.min.js"></script>
  <script>
    $(document).foundation();
  </script>

  </body>
</html>